services:
  - type: web
    name: flowdesk-frontend
    env: node
    region: oregon
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: https://flowdesk-backend.onrender.com
